# Generated by Django 4.1.7 on 2023-03-25 04:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NCRdelhiBoys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(auto_created=True, auto_now_add=True),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=30, verbose_name="NCR de munde da naam"
                    ),
                ),
                (
                    "contact_num",
                    models.PositiveIntegerField(
                        unique=True,
                        validators=[
                            django.core.validators.MaxValueValidator(999999999)
                        ],
                        verbose_name="NCR de munde da phone number",
                    ),
                ),
            ],
        ),
    ]
