# Generated by Django 4.1.7 on 2023-03-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mundeNCRde", "0005_alter_ncrdelhiboys_contact_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ncrdelhiboys",
            name="contact_num",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="NCR de munde da phone number"
            ),
        ),
    ]
